server:
  port: ${PORT:9090}

spring:
  application:
    name: admin-service
  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_URL:http://localhost:8761}
        username: ${BOOT_ADMIN_USERNAME:admin}
        password: ${BOOT_ADMIN_PASSWORD:medibook123}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:medibook_user}
    password: ${DB_PASSWORD:medibook_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

app:
  admins:
    - fullName: Shivam Mishra
      email: cy.shivam.m@gmail.com
      password: ${ADMIN_PASSWORD_1:ChangeMeAdmin#1}
    - fullName: Medibook
      email: help.medibook.grp@gmail.com
      password: ${ADMIN_PASSWORD_2:ChangeMeAdmin#2}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://admin:medibook123@localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${HOSTNAME:localhost}}
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
